# ********RoostGPT********
"""
Test generated by RoostGPT for test Exi-PW-Python-ClaudeAi using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219

ROOST_METHOD_HASH=create_profile_e234ba607e
ROOST_METHOD_SIG_HASH=create_profile_b09871bc39


# Test Scenarios for `create_profile` Function

## Understanding the Function

The `create_profile` function is a signal handler that creates a `Profile` instance whenever a new `User` instance is created. It's designed to be connected to Django's `post_save` signal for the `User` model.

## Test Scenarios

### Scenario 1: Profile Creation for New User
**Details:**
  **TestName:** test_profile_created_when_user_created
  **Description:** Verify that a Profile is automatically created when a new User is created.

**Execution:**
  **Arrange:** Set up the test environment by ensuring the signal is connected.
  **Act:** Create a new User instance.
  **Assert:** Check that a corresponding Profile instance exists for the newly created User.

**Validation:**
  This test ensures the core functionality of the signal handler - that it creates a Profile for each new User. This is essential for applications where user profiles are required for all users.

### Scenario 2: No Duplicate Profile Creation
**Details:**
  **TestName:** test_no_duplicate_profile_when_user_updated
  **Description:** Verify that updating an existing User does not create a duplicate Profile.

**Execution:**
  **Arrange:** Create a User and ensure it has a Profile.
  **Act:** Update the User's attributes and save.
  **Assert:** Verify that only one Profile exists for the User after the update.

**Validation:**
  This test ensures the signal handler respects the `created` flag and only creates profiles for new users, not when existing users are updated. This prevents data duplication.

### Scenario 3: Signal Connection Verification
**Details:**
  **TestName:** test_signal_connection
  **Description:** Verify that the `create_profile` function is properly connected to the `post_save` signal for the User model.

**Execution:**
  **Arrange:** Inspect the signal connections.
  **Act:** Check if `create_profile` is connected to `post_save` for the User model.
  **Assert:** Confirm the connection exists.

**Validation:**
  This test ensures the signal handler is properly connected, which is a prerequisite for the functionality to work as expected.

### Scenario 4: Profile Creation with Custom User Attributes
**Details:**
  **TestName:** test_profile_creation_with_custom_user_attributes
  **Description:** Verify that a Profile is created correctly when a User is created with custom attributes.

**Execution:**
  **Arrange:** Prepare custom attributes for a new User.
  **Act:** Create a User with these custom attributes.
  **Assert:** Verify a Profile is created and linked to the User.

**Validation:**
  This test ensures the signal handler works correctly regardless of the User's attributes, which is important for applications with diverse user data.

### Scenario 5: Profile Creation in Transaction
**Details:**
  **TestName:** test_profile_creation_in_transaction
  **Description:** Verify that Profile creation works correctly within a database transaction.

**Execution:**
  **Arrange:** Begin a database transaction.
  **Act:** Create a User within the transaction and then commit or rollback.
  **Assert:** Verify the Profile creation behavior matches the transaction outcome.

**Validation:**
  This test ensures the signal handler behaves correctly in transactional contexts, which is important for data integrity in complex operations.

### Scenario 6: Error Handling During Profile Creation
**Details:**
  **TestName:** test_error_handling_during_profile_creation
  **Description:** Verify how the system handles errors that might occur during Profile creation.

**Execution:**
  **Arrange:** Set up conditions that would cause Profile creation to fail (e.g., by mocking Profile.objects.create to raise an exception).
  **Act:** Create a new User, triggering the signal.
  **Assert:** Verify the system's error handling behavior.

**Validation:**
  This test ensures the application gracefully handles errors during Profile creation, which is important for system robustness.

### Scenario 7: Multiple User Creation
**Details:**
  **TestName:** test_multiple_user_creation
  **Description:** Verify that Profiles are correctly created when multiple Users are created in succession.

**Execution:**
  **Arrange:** Prepare data for multiple Users.
  **Act:** Create multiple Users in succession.
  **Assert:** Verify that each User has exactly one corresponding Profile.

**Validation:**
  This test ensures the signal handler works correctly in bulk operations, which is important for system scalability.
"""

# ********RoostGPT********
import pytest
from unittest.mock import patch, Mock
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from users.signals import create_profile
from models import Profile

class TestSignalsCreateProfile:
    
    @pytest.fixture
    def disconnect_signals(self):
        """Temporarily disconnect signals for isolated testing"""
        post_save.disconnect(create_profile, sender=User)
        yield
        post_save.connect(create_profile, sender=User)
    
    def test_profile_created_when_user_created(self, disconnect_signals):
        """Test that a Profile is automatically created when a new User is created"""
        # Manually connect the signal for this test
        post_save.connect(create_profile, sender=User)
        
        # Create a new user
        user = User.objects.create(
            username='testuser',
            email='test@example.com',
            password='password123'
        )
        
        # Check if a profile was created for this user
        profile = Profile.objects.filter(user=user).first()
        assert profile is not None, "Profile was not created for new user"
        assert profile.user == user, "Profile is not correctly associated with user"
    
    def test_no_duplicate_profile_when_user_updated(self, disconnect_signals):
        """Test that updating an existing User does not create a duplicate Profile"""
        # Manually connect the signal for this test
        post_save.connect(create_profile, sender=User)
        
        # Create a user (which should create a profile)
        user = User.objects.create(
            username='updateuser',
            email='update@example.com',
            password='password123'
        )
        
        # Count profiles before update
        profile_count_before = Profile.objects.filter(user=user).count()
        assert profile_count_before == 1, "Initial profile was not created"
        
        # Update the user
        user.first_name = "Updated"
        user.save()
        
        # Count profiles after update
        profile_count_after = Profile.objects.filter(user=user).count()
        assert profile_count_after == 1, "Duplicate profile was created on user update"
    
    def test_signal_connection(self):
        """Test that the create_profile function is properly connected to post_save signal"""
        # Get all receivers for post_save signal on User model
        receivers = post_save._live_receivers(sender=User)
        
        # Check if create_profile is among the receivers
        assert create_profile in receivers, "create_profile is not connected to post_save signal"
    
    @patch('models.Profile.objects.create')
    def test_error_handling_during_profile_creation(self, mock_create, disconnect_signals):
        """Test how the system handles errors during Profile creation"""
        # Set up the mock to raise an exception
        mock_create.side_effect = Exception("Profile creation failed")
        
        # Manually connect the signal for this test
        post_save.connect(create_profile, sender=User)
        
        # Create a user which should trigger the signal
        with pytest.raises(Exception) as excinfo:
            User.objects.create(
                username='erroruser',
                email='error@example.com',
                password='password123'
            )
        
        # Verify the exception was raised
        assert "Profile creation failed" in str(excinfo.value)
        
        # Verify the mock was called with the correct parameters
        mock_create.assert_called_once()
        args, kwargs = mock_create.call_args
        assert 'user' in kwargs, "User parameter was not passed to Profile.objects.create"
    
    def test_multiple_user_creation(self, disconnect_signals):
        """Test that Profiles are correctly created when multiple Users are created"""
        # Manually connect the signal for this test
        post_save.connect(create_profile, sender=User)
        
        # Create multiple users
        users = []
        for i in range(3):
            user = User.objects.create(
                username=f'multiuser{i}',
                email=f'multi{i}@example.com',
                password='password123'
            )
            users.append(user)
        
        # Check that each user has exactly one profile
        for user in users:
            profile_count = Profile.objects.filter(user=user).count()
            assert profile_count == 1, f"User {user.username} has {profile_count} profiles instead of 1"
