# ********RoostGPT********
"""
Test generated by RoostGPT for test Exi-PW-Python-ClaudeAi using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219

ROOST_METHOD_HASH=save_bc5b8f7074
ROOST_METHOD_SIG_HASH=save_fd2d25b57e


Scenario 1: Image Resizing When Dimensions Exceed Limits
Details:
  TestName: test_image_resizing_when_dimensions_exceed_limits
  Description: Verify that when an image with dimensions exceeding 300x300 pixels is saved, it gets resized to fit within those dimensions while maintaining aspect ratio.
Execution:
  Arrange: Create a model instance with an image that has dimensions larger than 300x300 pixels (e.g., 600x400).
  Act: Call the save method on the instance.
  Assert: Verify that the saved image dimensions are now within 300x300 pixels and the aspect ratio is maintained.
Validation:
  This test ensures the core functionality of the save method works correctly - automatically resizing large images to conserve storage space and ensure consistent display sizes across the application.

"""

# ********RoostGPT********
import os
import pytest
from unittest.mock import patch, MagicMock
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile
import django
from django.conf import settings

# Configure Django settings before importing models
settings.configure(
    INSTALLED_APPS=[
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'users',
    ],
    DATABASES={
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
)
django.setup()

# Create a mock Profile class for testing
class MockProfile:
    def save(self, *args, **kwargs):
        super_save = MagicMock()
        super_save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class TestProfileSave:
    """Test suite for the Profile.save method."""

    @pytest.fixture
    def mock_profile(self):
        """Create a mock profile with a test image."""
        profile = MockProfile()
        # Create a temporary directory for test images
        if not os.path.exists('test_media'):
            os.makedirs('test_media')
        return profile

    @pytest.fixture
    def create_test_image(self, size=(600, 400)):
        """Create a test image with specified dimensions."""
        # Create a test image with the specified size
        image = Image.new('RGB', size, color='red')
        image_io = BytesIO()
        image.save(image_io, format='JPEG')
        image_io.seek(0)
        
        # Create a SimpleUploadedFile
        return SimpleUploadedFile(
            name='test_image.jpg',
            content=image_io.read(),
            content_type='image/jpeg'
        )

    def test_image_resizing_when_dimensions_exceed_limits(self, mock_profile, create_test_image, tmp_path):
        """
        Test that images larger than 300x300 are resized while maintaining aspect ratio.
        """
        # Arrange
        test_image_path = os.path.join(tmp_path, "test_image.jpg")
        
        # Create a large test image (600x400)
        large_image = Image.new('RGB', (600, 400), color='red')
        large_image.save(test_image_path)
        
        # Configure the mock profile
        mock_profile.image = MagicMock()
        mock_profile.image.path = test_image_path
        
        # Act
        mock_profile.save()
        
        # Assert
        # Open the saved image to check its dimensions
        resized_image = Image.open(test_image_path)
        
        # Check that the image dimensions are now within limits
        assert resized_image.width <= 300, f"Image width should be <= 300, got {resized_image.width}"
        assert resized_image.height <= 300, f"Image height should be <= 300, got {resized_image.height}"
        
        # Check that aspect ratio is maintained (approximately)
        original_ratio = 600 / 400  # 1.5
        new_ratio = resized_image.width / resized_image.height
        assert abs(original_ratio - new_ratio) < 0.1, "Aspect ratio should be maintained"

    def test_small_image_not_resized(self, mock_profile, tmp_path):
        """
        Test that images smaller than 300x300 are not resized.
        """
        # Arrange
        test_image_path = os.path.join(tmp_path, "small_image.jpg")
        
        # Create a small test image (200x150)
        small_image = Image.new('RGB', (200, 150), color='blue')
        small_image.save(test_image_path)
        
        # Get original file size for comparison
        original_size = os.path.getsize(test_image_path)
        original_image = Image.open(test_image_path)
        original_width, original_height = original_image.size
        
        # Configure the mock profile
        mock_profile.image = MagicMock()
        mock_profile.image.path = test_image_path
        
        # Act
        mock_profile.save()
        
        # Assert
        # Open the saved image to check its dimensions
        saved_image = Image.open(test_image_path)
        saved_width, saved_height = saved_image.size
        
        # Dimensions should remain unchanged
        assert saved_width == original_width, "Width should not change for small images"
        assert saved_height == original_height, "Height should not change for small images"
        
        # File size should be approximately the same
        # Note: There might be minor differences due to re-saving
        current_size = os.path.getsize(test_image_path)
        assert abs(current_size - original_size) < 100, "File size should not change significantly"
