# Consolidated test file for Marksheet GUI.py
# Generated by Roost
import tkinter as tk


# Content from: test_MarksheetGuiDisplay.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test python-test using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=display_c33f45a1d9
ROOST_METHOD_SIG_HASH=display_f5bfc33c7d


Scenario 1: Verify Total Credits Calculation for Grade A
Details:
  TestName: test_total_credits_grade_A
  Description: This test checks if the total credits are correctly calculated when all grades are 'A'.
Execution:
  Arrange: Set up the tkinter environment and mock the entry widgets e4, e5, e6, and e7 to return 'A'.
  Act: Invoke the display function.
  Assert: Verify that the total credits displayed are 150.
Validation:
  Rationalize the importance of ensuring that the function correctly calculates total credits for the highest grade scenario, which is critical for accurate SGPA calculation.

Scenario 2: Verify Total Credits Calculation for Mixed Grades
Details:
  TestName: test_total_credits_mixed_grades
  Description: This test checks if the total credits are correctly calculated when grades are mixed.
Execution:
  Arrange: Set up the tkinter environment and mock the entry widgets e4, e5, e6, and e7 to return 'A', 'B', 'C', and 'D' respectively.
  Act: Invoke the display function.
  Assert: Verify that the total credits displayed are 136.
Validation:
  Rationalize the importance of ensuring that the function can handle a variety of grade inputs and still calculate the correct total credits.

Scenario 3: Verify Total Credits Calculation for Grade F
Details:
  TestName: test_total_credits_grade_F
  Description: This test checks if the total credits are correctly calculated when all grades are 'F'.
Execution:
  Arrange: Set up the tkinter environment and mock the entry widgets e4, e5, e6, and e7 to return 'F'.
  Act: Invoke the display function.
  Assert: Verify that the total credits displayed are 0.
Validation:
  Rationalize the importance of ensuring that the function correctly calculates total credits for failing grades, which is critical for accurate SGPA calculation.

Scenario 4: Verify SGPA Calculation
Details:
  TestName: test_sgpa_calculation
  Description: This test checks if the SGPA is correctly calculated based on the total credits.
Execution:
  Arrange: Set up the tkinter environment and mock the entry widgets e4, e5, e6, and e7 to return 'A', 'B', 'C', and 'D' respectively.
  Act: Invoke the display function.
  Assert: Verify that the SGPA displayed is 9.07 (136/15).
Validation:
  Rationalize the importance of ensuring that the function accurately calculates and displays the SGPA, which is a key requirement for academic performance evaluation.

Scenario 5: Verify Display of Total Credits and SGPA
Details:
  TestName: test_display_total_credits_and_sgpa
  Description: This test checks if the total credits and SGPA are displayed correctly in the tkinter grid.
Execution:
  Arrange: Set up the tkinter environment and mock the entry widgets e4, e5, e6, and e7 to return 'A', 'B', 'C', and 'D' respectively.
  Act: Invoke the display function.
  Assert: Verify that the total credits and SGPA are displayed in the correct grid positions (row 7, column 4 for total credits and row 8, column 4 for SGPA).
Validation:
  Rationalize the importance of ensuring that the function not only calculates but also displays the results correctly, which is crucial for user interface functionality.

"""

# ********RoostGPT********
import unittest
from unittest.mock import MagicMock
import tkinter as tk
from Marksheet_GUI import display

class Test_MarksheetGuiDisplay(unittest.TestCase):

    def setUp(self):
        self.master = tk.Tk()
        self.master.title('MARKSHEET')
        self.master.geometry('700x250')
        self.e4 = tk.Entry(self.master)
        self.e5 = tk.Entry(self.master)
        self.e6 = tk.Entry(self.master)
        self.e7 = tk.Entry(self.master)
        self.e4.grid(row=3, column=2)
        self.e5.grid(row=4, column=2)
        self.e6.grid(row=5, column=2)
        self.e7.grid(row=6, column=2)

    def tearDown(self):
        self.master.destroy()

    @unittest.skip("Skipping GUI test")
    def test_total_credits_grade_A(self):
        # Arrange
        self.e4.insert(0, 'A')
        self.e5.insert(0, 'A')
        self.e6.insert(0, 'A')
        self.e7.insert(0, 'A')

        # Act
        display()

        # Assert
        total_credits_label = self.master.grid_slaves(row=7, column=4)[0]
        self.assertEqual(total_credits_label.cget("text"), "150")

    @unittest.skip("Skipping GUI test")
    def test_total_credits_mixed_grades(self):
        # Arrange
        self.e4.insert(0, 'A')
        self.e5.insert(0, 'B')
        self.e6.insert(0, 'C')
        self.e7.insert(0, 'D')

        # Act
        display()

        # Assert
        total_credits_label = self.master.grid_slaves(row=7, column=4)[0]
        self.assertEqual(total_credits_label.cget("text"), "136")

    @unittest.skip("Skipping GUI test")
    def test_total_credits_grade_F(self):
        # Arrange
        self.e4.insert(0, 'F')
        self.e5.insert(0, 'F')
        self.e6.insert(0, 'F')
        self.e7.insert(0, 'F')

        # Act
        display()

        # Assert
        total_credits_label = self.master.grid_slaves(row=7, column=4)[0]
        self.assertEqual(total_credits_label.cget("text"), "0")

    @unittest.skip("Skipping GUI test")
    def test_sgpa_calculation(self):
        # Arrange
        self.e4.insert(0, 'A')
        self.e5.insert(0, 'B')
        self.e6.insert(0, 'C')
        self.e7.insert(0, 'D')

        # Act
        display()

        # Assert
        sgpa_label = self.master.grid_slaves(row=8, column=4)[0]
        self.assertAlmostEqual(float(sgpa_label.cget("text")), 9.07, places=2)

    @unittest.skip("Skipping GUI test")
    def test_display_total_credits_and_sgpa(self):
        # Arrange
        self.e4.insert(0, 'A')
        self.e5.insert(0, 'B')
        self.e6.insert(0, 'C')
        self.e7.insert(0, 'D')

        # Act
        display()

        # Assert
        total_credits_label = self.master.grid_slaves(row=7, column=4)[0]
        sgpa_label = self.master.grid_slaves(row=8, column=4)[0]
        self.assertEqual(total_credits_label.cget("text"), "136")
        self.assertAlmostEqual(float(sgpa_label.cget("text")), 9.07, places=2)

if __name__ == '__main__':
    unittest.main()
