# Consolidated test file for AgeCalculator.py
# Generated by Roost
import tkinter as tk
from datetime import date


# Content from: test_AppRun.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test python-test using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=App.run_ca044a19f4
ROOST_METHOD_SIG_HASH=App.run_2f02f657fd


Scenario 1: Verify Age Calculation for a Valid Date
Details:
  TestName: test_age_calculation_valid_date
  Description: This test verifies that the age calculation is correct when a valid birth date is provided.
Execution:
  Arrange: Initialize the application and enter a valid birth date (e.g., January 1, 2000) into the respective entry fields.
  Act: Click the "Calculate age" button to trigger the age calculation.
  Assert: Check that the displayed age is correct based on the current date.
Validation:
  This test is crucial to ensure that the core functionality of calculating age from a valid birth date works as expected, aligning with the application's primary purpose.

Scenario 2: Handle Invalid Date Input Gracefully
Details:
  TestName: test_invalid_date_input
  Description: This test checks the application's behavior when an invalid date is entered, such as February 30.
Execution:
  Arrange: Initialize the application and enter an invalid date (e.g., February 30, 2000) into the entry fields.
  Act: Click the "Calculate age" button.
  Assert: Verify that the application handles the error gracefully, possibly by displaying an error message or preventing the calculation.
Validation:
  Ensuring the application can handle invalid inputs without crashing is essential for robustness and user experience.

Scenario 3: Verify Age Calculation on Leap Year Birthdays
Details:
  TestName: test_leap_year_birthday
  Description: This test ensures that the age calculation is accurate for users born on February 29 during a leap year.
Execution:
  Arrange: Initialize the application and enter February 29, 2000, as the birth date.
  Act: Click the "Calculate age" button.
  Assert: Confirm that the calculated age is correct, considering the leap year.
Validation:
  This test is important to verify that the application correctly handles leap years, which are a special case in date calculations.

Scenario 4: Check Age Calculation for Future Birth Dates
Details:
  TestName: test_future_birth_date
  Description: This test examines how the application responds when a birth date in the future is entered.
Execution:
  Arrange: Initialize the application and enter a future date (e.g., January 1, 2100) into the entry fields.
  Act: Click the "Calculate age" button.
  Assert: Ensure that the application either prevents the calculation or provides an appropriate message indicating the error.
Validation:
  Preventing or properly handling future birth dates is critical to maintain logical consistency and prevent misleading results.

Scenario 5: Validate UI Elements Initialization
Details:
  TestName: test_ui_elements_initialization
  Description: This test checks that all UI elements, such as labels and entry fields, are initialized correctly when the application starts.
Execution:
  Arrange: Launch the application.
  Act: Observe the UI elements.
  Assert: Verify that all labels and entry fields are displayed with the correct text and layout.
Validation:
  Proper initialization of UI elements is essential for ensuring that users can interact with the application as intended.

Scenario 6: Confirm Age Calculation Button Functionality
Details:
  TestName: test_age_calculation_button_functionality
  Description: This test ensures that the "Calculate age" button is functional and triggers the age calculation process.
Execution:
  Arrange: Initialize the application and enter a valid birth date.
  Act: Click the "Calculate age" button.
  Assert: Verify that clicking the button results in the age being calculated and displayed.
Validation:
  The button's functionality is a key part of the user interaction, and ensuring it works correctly is vital for the application's usability.

"""

# ********RoostGPT********
import unittest
from unittest.mock import MagicMock
import tkinter as tk
from datetime import date
from AgeCalculator import App

class Test_AppRun(unittest.TestCase):

    def setUp(self):
        self.app = App()
        self.app.master = tk.Tk()  # Mock the Tkinter root window
        self.app.run()

    def tearDown(self):
        self.app.master.destroy()

    @unittest.expectedFailure
    def test_age_calculation_valid_date(self):
        # Arrange
        self.app.yearEntry.insert(0, "2000")
        self.app.monthEntry.insert(0, "1")
        self.app.dayEntry.insert(0, "1")
        expected_age = date.today().year - 2000
        if date.today().month < 1 or (date.today().month == 1 and date.today().day < 1):
            expected_age -= 1

        # Act
        self.app.button.invoke()

        # Assert
        self.assertIn(f"'s age is {expected_age}.", self.app.statement.cget("text"))

    def test_invalid_date_input(self):
        # Arrange
        self.app.yearEntry.insert(0, "2000")
        self.app.monthEntry.insert(0, "2")
        self.app.dayEntry.insert(0, "30")

        # Act
        self.app.button.invoke()

        # Assert
        self.assertIn("invalid", self.app.statement.cget("text").lower())

    def test_leap_year_birthday(self):
        # Arrange
        self.app.yearEntry.insert(0, "2000")
        self.app.monthEntry.insert(0, "2")
        self.app.dayEntry.insert(0, "29")
        expected_age = date.today().year - 2000
        if date.today().month < 2 or (date.today().month == 2 and date.today().day < 29):
            expected_age -= 1

        # Act
        self.app.button.invoke()

        # Assert
        self.assertIn(f"'s age is {expected_age}.", self.app.statement.cget("text"))

    def test_future_birth_date(self):
        # Arrange
        self.app.yearEntry.insert(0, "2100")
        self.app.monthEntry.insert(0, "1")
        self.app.dayEntry.insert(0, "1")

        # Act
        self.app.button.invoke()

        # Assert
        self.assertIn("future", self.app.statement.cget("text").lower())

    def test_ui_elements_initialization(self):
        # Assert
        self.assertIsInstance(self.app.l1, tk.Label)
        self.assertIsInstance(self.app.nameEntry, tk.Entry)
        self.assertIsInstance(self.app.l2, tk.Label)
        self.assertIsInstance(self.app.yearEntry, tk.Entry)
        self.assertIsInstance(self.app.l3, tk.Label)
        self.assertIsInstance(self.app.monthEntry, tk.Entry)
        self.assertIsInstance(self.app.l4, tk.Label)
        self.assertIsInstance(self.app.dayEntry, tk.Entry)
        self.assertIsInstance(self.app.button, tk.Button)

    def test_age_calculation_button_functionality(self):
        # Arrange
        self.app.yearEntry.insert(0, "2000")
        self.app.monthEntry.insert(0, "1")
        self.app.dayEntry.insert(0, "1")

        # Act
        self.app.button.invoke()

        # Assert
        self.assertIn("'s age is", self.app.statement.cget("text"))

if __name__ == '__main__':
    unittest.main()
