# Test generated by RoostGPT for test python-audio-book using AI Type Open AI and AI Model gpt-4

import unittest
from unittest.mock import AsyncMock, MagicMock
from Discord_bot_python import on_message

class TestOnMessage(unittest.TestCase):

    def setUp(self):
        self.message = MagicMock()
        self.message.channel.send = AsyncMock()

    def test_On_message_0793b7ef2f(self):
        self.message.content = "hello"
        self.message.author = "TestUser"
        on_message(self.message)
        self.message.channel.send.assert_called_with("Hello, I am Cheatbot, here to help you cheat!")

        self.message.content = "cheat ping"
        on_message(self.message)
        self.message.channel.send.assert_called_with(f'{round(client.latency*1000)}ms')

        self.message.content = "cheat wiki Python"
        on_message(self.message)
        self.message.channel.send.assert_called()

        self.message.content = "cheat question What is Python? 4"
        on_message(self.message)
        self.message.channel.send.assert_called()

        self.message.content = "cheat help"
        on_message(self.message)
        self.message.channel.send.assert_called_with("""Commands
-------------------------------------------------------------------------------------------------------
1 : cheat wiki something to search
This command will search wiki and give a short description, along with a link to that page
2 : cheat error some error
This command will search for your error on stack overflow and give links to 3 answers
------------------------------------------------------------------------------------------------------
Examples
-------------------------------------------------------------------------------------------------------
cheat wiki data structures
cheat error SIGSEV""")

        self.message.content = "cheat error NameError 3"
        on_message(self.message)
        self.message.channel.send.assert_called()

if __name__ == '__main__':
    unittest.main()
