# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from string import ascii_lowercase as alphabet

def isCharacter(element):
    for letter in alphabet:
        if(element.lower() == letter):
            return True
    return False

class TestIsCharacter(unittest.TestCase):

    def test_IsCharacter_5d8094df9c(self):
        # Test case 1: Check with a character that is in alphabet
        result = isCharacter('a')
        self.assertEqual(result, True, "Expected output is True, but got {0}".format(result))

        # Test case 2: Check with a character that is not in alphabet
        result = isCharacter('1')
        self.assertEqual(result, False, "Expected output is False, but got {0}".format(result))

        # Test case 3: Check with a character in uppercase
        result = isCharacter('A')
        self.assertEqual(result, True, "Expected output is True, but got {0}".format(result))

        # Test case 4: Check with a special character
        result = isCharacter('@')
        self.assertEqual(result, False, "Expected output is False, but got {0}".format(result))

if __name__ == '__main__':
    unittest.main()
