# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import encrypt

class TestEncrypt(unittest.TestCase):

    def TestEncrypt_71580cd1e0(self):
        # Test case 1: Normal scenario
        result = encrypt("Hello World", 2)
        self.assertEqual(result, "Jgnnq Yqtnf")
        
        # Test case 2: Empty string
        result = encrypt("", 2)
        self.assertEqual(result, "")
        
        # Test case 3: String with special characters
        result = encrypt("Hello @ World!", 2)
        self.assertEqual(result, "Jgnnq @ Yqtnf!")
        
        # Test case 4: String with numbers
        result = encrypt("Hello World 123", 2)
        self.assertEqual(result, "Jgnnq Yqtnf 345")
        
        # Test case 5: Negative encryptNum
        result = encrypt("Hello World", -2)
        self.assertEqual(result, "Fcjjm Umpjb")
        
        # Test case 6: encryptNum as 0
        result = encrypt("Hello World", 0)
        self.assertEqual(result, "Hello World")
        
        # Test case 7: Large encryptNum
        result = encrypt("Hello World", 100)
        self.assertEqual(result, "Dahhk Sknhz")

if __name__ == '__main__':
    unittest.main()
