# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest

# The method to test
def isSpecialChar(element):
    specChar = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '+', '=']
    for char in specChar:
        if(element == char):
            return True
    return False

# Test cases
class TestIsSpecialChar(unittest.TestCase):

    def test_isSpecialChar_8fe3ae6f12(self):
        self.assertEqual(isSpecialChar('!'), True)
        self.assertEqual(isSpecialChar('@'), True)
        self.assertEqual(isSpecialChar('#'), True)
        self.assertEqual(isSpecialChar('a'), False)
        self.assertEqual(isSpecialChar('1'), False)
        self.assertEqual(isSpecialChar(''), False)

if __name__ == '__main__':
    unittest.main()
