# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest

def isNumber(element):
    for i in range(0,10):
        if(int(element) == i):
            return True
    return False

class TestIsNumber(unittest.TestCase):
    
    def TestIsNumber_ed9ccec17b(self):
        self.assertTrue(isNumber(4))  # Test with an integer that is in the range
        self.assertFalse(isNumber(10))  # Test with an integer that is not in the range
        self.assertTrue(isNumber('2'))  # Test with a string that can be converted to an integer in the range
        self.assertFalse(isNumber('a'))  # Test with a string that can't be converted to an integer
        self.assertFalse(isNumber(None))  # Test with None

if __name__ == '__main__':
    unittest.main()
