# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import isCharacter

class TestIsCharacter(unittest.TestCase):

    def test_isCharacter_valid(self):
        self.assertTrue(isCharacter('a'))
        self.assertTrue(isCharacter('Z'))

    def test_isCharacter_invalid(self):
        self.assertFalse(isCharacter('1'))
        self.assertFalse(isCharacter('&'))

    def test_isCharacter_empty(self):
        self.assertFalse(isCharacter(''))

    def test_isCharacter_special(self):
        self.assertFalse(isCharacter(' '))

if __name__ == '__main__':
    unittest.main()
