# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest

def isNumber(element):
    for i in range(0,10):
        if(int(element) == i):
            return True
    return False

class TestIsNumber(unittest.TestCase):

    def test_isNumber(self):
        self.assertEqual(isNumber(5), True, "Should be True")
        self.assertEqual(isNumber(10), False, "Should be False")

    def test_isNumber_with_string(self):
        with self.assertRaises(ValueError):
            isNumber("a")

    def test_isNumber_with_negative_number(self):
        self.assertEqual(isNumber(-1), False, "Should be False")

if __name__ == '__main__':
    unittest.main()
